on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule: [cron: "40 1 * * *"]

name: ci

jobs:
  # build, test all supported targets
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
            # msrv
          - 1.65.0
        features:
          - --no-default-features --features xz
          - --no-default-features --features gzip
          - --no-default-features --features gzip,xz
          - --no-default-features --features xz-static
          # default features
          -

    steps:
      - run: sudo apt-get install -y squashfs-tools
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo build ${{ matrix.features }}
      - run: RUST_LOG=info cargo test --release ${{ matrix.features }}

  # benchmark
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench

  # fmt and clippy on nightly builds
  fmt-clippy-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      # fmt
      - run: cargo fmt --all -- --check

      # clippy
      - run: cargo clippy -- -D warnings
